"""02_create_login_log_table

Revision ID: defed557f345
Revises: c03f71c012e9
Create Date: 2021-01-19 10:48:11.793676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence, DropSequence

# revision identifiers, used by Alembic.
revision = 'defed557f345'
down_revision = 'c03f71c012e9'
branch_labels = None
depends_on = None


def upgrade():
    op.execute(CreateSequence(Sequence('login_log_id_seq')))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_log',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('login_log_id_seq')"), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_ip', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    op.execute(DropSequence(Sequence('login_log_id_seq')))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_log')
    # ### end Alembic commands ###
